name: Run the tests, build the image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build the package
        run: mvn --batch-mode -DskipTests package

      - name: Run the unit tests
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Build and push the image
        run: |
          docker login --username tlion1069 --password ${{secrets.ACCESS_TOKEN}} ghcr.io
          docker build -t ghcr.io/tlion1069/coffee:latest --file Dockerfile .
          docker push ghcr.io/tlion1069/coffee:latest
          
